# Generated by Django 5.2 on 2025-05-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='price_currency',
            field=models.CharField(choices=[('EUR', 'Euro €'), ('USD', 'US dollar $')], default='EUR', max_length=4),
        ),
    ]
