"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django.
"""

import sys
from pathlib import Path
from datetime import timedelta

import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(BASE_DIR / "src"))
sys.path.append(str(BASE_DIR))  # -> ecommerce directory

# Take environment variables from .env file if it exists
env_file = BASE_DIR / ".env"

if env_file.exists():
    environ.Env.read_env(env_file)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS")
CSRF_FAILURE_VIEW = "utils.views.csrf_failure"

# Application definition

INSTALLED_APPS = [
    # built in
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # apps
    "account",
    "permissions",
    "catalogue",
    "products",
    "basket",
    "inventory",
    "order",
    # third-party apps
    "channels",
    "corsheaders",
    "treebeard",
    "strawberry_django",
    "whitenoise.runserver_nostatic",
]

if DEBUG:
    INSTALLED_APPS += [
        "debug_toolbar",
        "django_erd_generator",
    ]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "authentication.middleware.JWTCookieAuthMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    MIDDLEWARE += [
        "strawberry_django.middlewares.debug_toolbar.DebugToolbarMiddleware",
    ]


ROOT_URLCONF = "sandbox.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "src" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# WSGI_APPLICATION = "wsgi.application"
ASGI_APPLICATION = "sandbox.asgi.application"

# Database

DATABASES = {
    "default": {
        "ENGINE": env("DATABASE_ENGINE"),
        "NAME": env("DATABASE_NAME"),
        "USER": env("DATABASE_USER"),
        "PASSWORD": env("DATABASE_PASSWORD"),
        "HOST": env("DATABASE_HOST"),
        "PORT": env("DATABASE_PORT"),
    }
}


# Caches
CACHES = {
    "default": {
        "BACKEND": env("CACHE_BACKEND"),
        "LOCATION": env("CACHE_LOCATION"),
        "TIMEOUT": env("CACHE_TIMEOUT"),
    }
}

# User model

AUTH_USER_MODEL = "account.User"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# Default primary key field type

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


# LOGGING

LOG_DIR = Path(BASE_DIR) / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "sql_console": {
            "()": "src.utils.formatters.PrettySQLFormatter",
            "format": "\n[SQL] (%(duration).3f s)\n%(sql_pretty)s\n",
        },
        "sql_file": {
            "()": "src.utils.formatters.RawSQLFormatter",
            "format": "%(asctime)s (%(duration).3f) %(sql)s",
        },
    },
    "handlers": {
        "console_sql": {
            "class": "logging.StreamHandler",
            "formatter": "sql_console",
        },
        "file_sql": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "sql.log"),
            "formatter": "sql_file",
            "mode": "a",
            "maxBytes": 7000,
            "backupCount": 2,
            "delay": True,
            "encoding": "utf-8",
        },
    },
    "loggers": {},
}

if DEBUG:
    LOGGING["loggers"]["django.db.backends"] = {
        "handlers": ["console_sql"],
        "level": "DEBUG",
        "propagate": False,
    }
elif env("LOGGING_QUERIES", default=False):
    LOGGING["loggers"]["django.db.backends"] = {
        "level": "ERROR",
        "handlers": ["file_sql"],
        "propagate": False,
    }

# CORS configuration
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOW_CREDENTIALS = env.bool(
    "CORS_ALLOW_CREDENTIALS", default=False
)  # Allow cookies to be sent/received


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


DEBUG_TOOLBAR_CONFIG = {
    "USE_SHADOW_DOM": False,
}


STRAWBERRY_DJANGO = {
    "FIELD_DESCRIPTION_FROM_HELP_TEXT": True,
    "TYPE_DESCRIPTION_FROM_MODEL_DOCSTRING": True,
    "MAP_AUTO_ID_AS_GLOBAL_ID": True,
    "GENERATE_ENUMS_FROM_CHOICES": True,
}

JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=env.int("ACCESS_TOKEN_LIFETIME_MINUTES", default=5)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=env.int("REFRESH_TOKEN_LIFETIME_DAYS", default=7)
    ),
    "JWT_AUTH_EXEMPT_PATHS": ("/admin/",),
    "JWT_SIGN_KEY": env("JWT_SIGN_KEY"),
    "FIELD_ENCRYPTION_KEY": env("FIELD_ENCRYPTION_KEY"),
    "REFRESH_COOKIE_PATH": "/dashboard/graphql",
}

# EMAIL
default_email_backend = (
    "django.core.mail.backends.filebased.EmailBackend"
    if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_BACKEND = env("EMAIL_BACKEND", default=default_email_backend)
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="ecommerce@django")
EMAIL_FILE_PATH = BASE_DIR / "logs" / "emails"


# REDIS
import redis.asyncio as redis
from redis.asyncio.retry import Retry
from redis.backoff import ExponentialBackoff

REDIS_URL = env("REDIS_URL")
REDIS_CLIENT = redis.Redis.from_url(  # Singleton
    REDIS_URL,
    max_connections=50,
    socket_connect_timeout=10,
    socket_timeout=10,
    retry=Retry(ExponentialBackoff(cap=2, base=0.1), retries=3),
    retry_on_error=[TimeoutError, ConnectionError],
    health_check_interval=30,
    socket_keepalive=True,
    decode_responses=True,
)
