# Generated by Django 5.1.3 on 2024-12-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-updated_at',)},
        ),
    ]
