# Generated by Django 6.0.7 on 2026-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured metadata.', null=True),
        ),
    ]
