# Generated by Django 5.1.3 on 2024-12-04 16:29

import django.db.models.deletion
import products.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, auto_created='title', max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('value_type', models.CharField(choices=[('charactor', 'Charactor'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'True / False'), ('date', 'Date'), ('datetime', 'Date - Time'), ('time', 'Time')], default='charactor', max_length=20)),
                ('require', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, auto_created='title', max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('require_shipping', models.BooleanField(default=True)),
                ('track_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', products.fields.DynamicValueField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='products.ProductAttributeValue', to='products.productattribute'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='products.productclass'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productclass'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product_class', 'slug')},
        ),
    ]
