# Generated by Django 6.0.7 on 2026-08-15 13:07

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured metadata.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("dropdown", "Dropdown"),
                            ("multiselect", "Multiselect"),
                            ("file", "File"),
                            ("reference", "Reference"),
                            ("single-reference", "Single Reference"),
                            ("numeric", "Numeric"),
                            ("rich-text", "Rich Text"),
                            ("plain-text", "Plain Text"),
                            ("swatch", "Swatch"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("date-time", "Date Time"),
                        ],
                        default="dropdown",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MM", "Millimeter"),
                            ("CM", "Centimeter"),
                            ("DM", "Decimeter"),
                            ("M", "Meter"),
                            ("KM", "Kilometers"),
                            ("INCH", "Inch"),
                            ("G", "Gram"),
                            ("LB", "Pound"),
                            ("OZ", "Ounce"),
                            ("KG", "kg"),
                            ("SQ_MM", "Square millimeter"),
                            ("SQ_CM", "Square centimeters"),
                            ("SQ_DM", "Square decimeter"),
                            ("SQ_M", "Square meters"),
                            ("SQ_INCH", "Square inches"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("value_required", models.BooleanField(blank=True, default=False)),
                ("variant_only", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProductClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        auto_created="title",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured metadata.",
                        null=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=250)),
                ("require_shipping", models.BooleanField(default=True)),
                ("track_stock", models.BooleanField(default=True)),
                ("abstract", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "product classes",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        auto_created="title",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title for the page.",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta description.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured metadata.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description."),
                ),
                ("title", models.CharField(db_index=True, max_length=250)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                # ('categories', models.ManyToManyField(related_name='products', through='catalogue.ProductCategory', to='catalogue.category')),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.productclass",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label used to display the attribute value to users.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                ("rich_text", models.JSONField(blank=True, null=True)),
                ("plain_text", models.TextField(blank=True, null=True)),
                ("boolean", models.BooleanField(blank=True, null=True)),
                ("date_time", models.DateTimeField(blank=True, null=True)),
                ("numeric", models.FloatField(blank=True, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="products.attribute",
                    ),
                ),
                # ('refreence_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='catalogue.category')),
                (
                    "reference_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("label", "attribute")},
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="product_class",
            field=models.ManyToManyField(
                blank=True, related_name="attributes", to="products.productclass"
            ),
        ),
        migrations.CreateModel(
            name="ProductClassEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        help_text="The class receiving inheritance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="products.productclass",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        help_text="Parent class that this class inherits from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="products.productclass",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productclass",
            name="parents",
            field=models.ManyToManyField(
                blank=True,
                related_name="children",
                through="products.ProductClassEdge",
                through_fields=("child", "parent"),
                to="products.productclass",
            ),
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        help_text="Controls the display order.",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured metadata.",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products"),
                ),
                ("caption", models.CharField(blank=True, max_length=250)),
                ("published", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-sort_order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title for the page.",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta description.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "language_code",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("en", "English"),
                            ("fa", "Persian"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("ar", "Arabic"),
                        ],
                        default="en",
                        help_text="Language of this translation.",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "translation of products",
            },
        ),
        migrations.CreateModel(
            name="AttributeTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title for the page.",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta description.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "language_code",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("en", "English"),
                            ("fa", "Persian"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("ar", "Arabic"),
                        ],
                        default="en",
                        help_text="Language of this translation.",
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="products.attribute",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "translation of product attributes",
                "indexes": [
                    models.Index(
                        fields=["attribute"], name="products_at_attribu_55c09d_idx"
                    )
                ],
                "unique_together": {("language_code", "attribute")},
            },
        ),
        migrations.CreateModel(
            name="AttributeValueTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title for the page.",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta description.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "language_code",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("en", "English"),
                            ("fa", "Persian"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("ar", "Arabic"),
                        ],
                        default="en",
                        help_text="Language of this translation.",
                        max_length=2,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                ("rich_text", models.JSONField(blank=True, null=True)),
                ("plain_text", models.TextField(blank=True, null=True)),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="products.attributevalue",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "translation of product attribute value",
                "indexes": [
                    models.Index(
                        fields=["attribute_value"],
                        name="products_at_attribu_18c4ff_idx",
                    )
                ],
                "unique_together": {("language_code", "attribute_value")},
            },
        ),
        migrations.CreateModel(
            name="AssignedProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        help_text="Controls the display order.",
                        null=True,
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributevalues",
                        to="products.attributevalue",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributevalues",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "value")},
            },
        ),
        migrations.CreateModel(
            name="AttributeProductClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        help_text="Controls the display order.",
                        null=True,
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributeproductclass",
                        to="products.attribute",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributeproductclass",
                        to="products.productclass",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "pk"),
                "unique_together": {("attribute", "product_type")},
            },
        ),
        migrations.AddConstraint(
            model_name="productclassedge",
            constraint=models.UniqueConstraint(
                fields=("parent", "child"), name="unique_product_class_edge"
            ),
        ),
        migrations.AddConstraint(
            model_name="productclassedge",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("child")), _negated=True),
                name="prevent_self_edge",
            ),
        ),
        migrations.AddIndex(
            model_name="producttranslation",
            index=models.Index(
                fields=["product"], name="products_pr_product_01ff69_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="producttranslation",
            unique_together={("language_code", "product")},
        ),
    ]
