# Generated by Django 5.1.3 on 2024-12-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('language_code', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=250)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.productattribute')),
            ],
            options={
                'indexes': [models.Index(fields=['attribute'], name='products_pr_attribu_d648e1_idx')],
                'unique_together': {('language_code', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValueTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('language_code', models.CharField(max_length=35)),
                ('value', models.TextField(blank=True)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.productattributevalue')),
            ],
            options={
                'indexes': [models.Index(fields=['attribute_value'], name='products_pr_attribu_db43a6_idx')],
                'unique_together': {('language_code', 'attribute_value')},
            },
        ),
        migrations.CreateModel(
            name='ProductTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('language_code', models.CharField(max_length=35)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='products_pr_product_27005f_idx')],
                'unique_together': {('language_code', 'product')},
            },
        ),
    ]
