# Generated by Django 6.0.7 on 2026-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_assignedvariantattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(related_name='products', through='products.AssignedProductAttributeValue', to='products.attributevalue'),
        ),
    ]
