# Generated by Django 6.0.7 on 2026-08-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_attribute_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevariant',
            old_name='product_type',
            new_name='product_class',
        ),
        migrations.AlterUniqueTogether(
            name='attributevariant',
            unique_together={('attribute', 'product_class')},
        ),
    ]
