# Generated by Django 5.1.3 on 2024-12-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productclassrelation_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='abstract',
            field=models.BooleanField(default=False),
        ),
    ]
