# Generated by Django 5.1.3 on 2024-12-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productattributetranslate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributetranslate',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', max_length=35),
        ),
        migrations.AlterField(
            model_name='productattributevaluetranslate',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', max_length=35),
        ),
        migrations.AlterField(
            model_name='producttranslate',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', max_length=35),
        ),
    ]
