# Generated by Django 5.1.3 on 2025-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productattributetranslate_language_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product_class',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_class',
            field=models.ManyToManyField(related_name='attributes', to='products.productclass'),
        ),
    ]
