# Generated by Django 5.1.3 on 2025-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='product_class',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='products.productclass'),
        ),
    ]
