# Generated by Django 5.1.3 on 2025-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_productcategory'),
        ('products', '0010_alter_productattribute_product_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', through='catalogue.ProductCategory', to='catalogue.category'),
        ),
    ]
