# Generated by Django 5.2 on 2025-05-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='sort_order',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
