# Generated by Django 5.2 on 2025-05-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productmedia_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ('-sort_order',)},
        ),
    ]
