# Generated by Django 6.0.7 on 2026-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productmedia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='productattributetranslate',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=35),
        ),
        migrations.AlterField(
            model_name='productattributetranslate',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productattributetranslate',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevaluetranslate',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=35),
        ),
        migrations.AlterField(
            model_name='productattributevaluetranslate',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevaluetranslate',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='sort_order',
            field=models.IntegerField(db_index=True, help_text='Controls the display order.', null=True),
        ),
        migrations.AlterField(
            model_name='producttranslate',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=35),
        ),
        migrations.AlterField(
            model_name='producttranslate',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='producttranslate',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True),
        ),
    ]
