# Generated by Django 6.0.7 on 2026-07-24 11:02

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributetranslate',
            name='language_code',
            field=django_choices_field.fields.TextChoicesField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=2),
        ),
        migrations.AlterField(
            model_name='productattributevaluetranslate',
            name='language_code',
            field=django_choices_field.fields.TextChoicesField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=2),
        ),
        migrations.AlterField(
            model_name='producttranslate',
            name='language_code',
            field=django_choices_field.fields.TextChoicesField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=2),
        ),
    ]
