# Generated by Django 6.0.7 on 2026-07-31 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productattributetranslate_language_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclass',
            name='bases',
        ),
        migrations.CreateModel(
            name='ProductClassEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='products.productclass')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='products.productclass')),
            ],
        ),
        migrations.AddField(
            model_name='productclass',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', through='products.ProductClassEdge', through_fields=('child', 'parent'), to='products.productclass'),
        ),
        migrations.DeleteModel(
            name='ProductClassRelation',
        ),
        migrations.AddConstraint(
            model_name='productclassedge',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_product_class_edge'),
        ),
        migrations.AddConstraint(
            model_name='productclassedge',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='prevent_self_edge'),
        ),
    ]
