# Generated by Django 6.0.7 on 2026-08-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_productclass_bases_productclassedge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclassedge',
            name='child',
            field=models.ForeignKey(help_text='The class receiving inheritance.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='products.productclass'),
        ),
        migrations.AlterField(
            model_name='productclassedge',
            name='parent',
            field=models.ForeignKey(help_text='Parent class that this class inherits from.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='products.productclass'),
        ),
    ]
