# Generated by Django 6.0.7 on 2026-08-15 09:27

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_categorytranslation_language_code_and_more'),
        ('products', '0018_alter_productclassedge_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, help_text='Controls the display order.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured metadata.', null=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('input_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('multiselect', 'Multiselect'), ('file', 'File'), ('reference', 'Reference'), ('single-reference', 'Single Reference'), ('numeric', 'Numeric'), ('rich-text', 'Rich Text'), ('plain-text', 'Plain Text'), ('swatch', 'Swatch'), ('boolean', 'Boolean'), ('date', 'Date'), ('date-time', 'Date Time')], default='dropdown', max_length=20)),
                ('unit', models.CharField(blank=True, choices=[('MM', 'Millimeter'), ('CM', 'Centimeter'), ('DM', 'Decimeter'), ('M', 'Meter'), ('KM', 'Kilometers'), ('INCH', 'Inch'), ('G', 'Gram'), ('LB', 'Pound'), ('OZ', 'Ounce'), ('KG', 'kg'), ('SQ_MM', 'Square millimeter'), ('SQ_CM', 'Square centimeters'), ('SQ_DM', 'Square decimeter'), ('SQ_M', 'Square meters'), ('SQ_INCH', 'Square inches')], max_length=100, null=True)),
                ('value_required', models.BooleanField(blank=True, default=False)),
                ('variant_only', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeProductClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, help_text='Controls the display order.', null=True)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True)),
                ('language_code', django_choices_field.fields.TextChoicesField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=2)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'translation of product attributes',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Human-readable label used to display the attribute value to users.', max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('rich_text', models.JSONField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True, null=True)),
                ('boolean', models.BooleanField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('numeric', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True)),
                ('language_code', django_choices_field.fields.TextChoicesField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=2)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('rich_text', models.JSONField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'translation of product attribute value',
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True)),
                ('language_code', django_choices_field.fields.TextChoicesField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=2)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'translation of products',
            },
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product_class',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.AlterUniqueTogether(
            name='productattributetranslate',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='productattributetranslate',
            name='products_pr_attribu_d648e1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productattributevaluetranslate',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='productattributevaluetranslate',
            name='products_pr_attribu_db43a6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='producttranslate',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='producttranslate',
            name='products_pr_product_27005f_idx',
        ),
        migrations.AddField(
            model_name='assignedproductattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributevalues', to='products.product'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='product_class',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='products.productclass'),
        ),
        migrations.AddField(
            model_name='attributeproductclass',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributeproductclass', to='products.attribute'),
        ),
        migrations.AddField(
            model_name='attributeproductclass',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributeproductclass', to='products.productclass'),
        ),
        migrations.AddField(
            model_name='attributetranslation',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.attribute'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='reference_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='products.product'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='refreence_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='catalogue.category'),
        ),
        migrations.AddField(
            model_name='assignedproductattributevalue',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributevalues', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='attributevaluetranslation',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='productattributetranslate',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevaluetranslate',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='producttranslate',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='attributeproductclass',
            unique_together={('attribute', 'product_type')},
        ),
        migrations.AddIndex(
            model_name='attributetranslation',
            index=models.Index(fields=['attribute'], name='products_at_attribu_55c09d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributetranslation',
            unique_together={('language_code', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('label', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='assignedproductattributevalue',
            unique_together={('product', 'value')},
        ),
        migrations.AddIndex(
            model_name='attributevaluetranslation',
            index=models.Index(fields=['attribute_value'], name='products_at_attribu_18c4ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevaluetranslation',
            unique_together={('language_code', 'attribute_value')},
        ),
        migrations.AddIndex(
            model_name='producttranslation',
            index=models.Index(fields=['product'], name='products_pr_product_01ff69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('language_code', 'product')},
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeTranslate',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValueTranslate',
        ),
        migrations.DeleteModel(
            name='ProductTranslate',
        ),
    ]
