# Generated by Django 6.0.7 on 2026-08-15 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '__first__'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured metadata.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.', verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.', verbose_name='Date updated')),
                ('shipping_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(max_length=120)),
                ('date_placed', models.DateTimeField(db_index=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Guest email address')),
                ('currency', models.CharField(max_length=12)),
                ('total_incl_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Order total (include tax)')),
                ('total_excl_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Order total (exclude tax)')),
                ('shipping_incl_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping charge (include tax)')),
                ('shipping_excl_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping charge (exclude tax)')),
                ('shipping_method', models.CharField(blank=True, max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.', verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.', verbose_name='Date updated')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('line_price_incl_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (include tax)')),
                ('line_price_excl_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (exclude tax)')),
                ('line_price_before_discounts_incl_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price before discounts (include tax)')),
                ('line_price_before_discounts_excl_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price before discounts (exclude tax)')),
                ('unit_price_incl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit Price (include tax)')),
                ('unit_price_excl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit Price (exclude tax)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('stockrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='inventory.stockrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
