# Generated by Django 5.2 on 2025-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='line_price_before_discounts_excl_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price before discounts (exclude tax)'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='line_price_before_discounts_incl_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price before discounts (include tax)'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='line_price_excl_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (exclude tax)'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='line_price_incl_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (include tax)'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='unit_price_incl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit Price (include tax)'),
        ),
    ]
