# Generated by Django 5.2 on 2025-05-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_metadata_and_more'),
        ('products', '0013_alter_productmedia_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
