# Generated by Django 6.0.7 on 2026-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderline_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.', verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.', verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='order',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.', verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.', verbose_name='Date updated'),
        ),
    ]
