# Generated by Django 5.2 on 2025-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated'),
        ),
    ]
