# Generated by Django 6.0.7 on 2026-08-15 13:08

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, auto_created='name', max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured metadata.', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description.')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='category-background')),
                ('background_caption', models.CharField(blank=True, max_length=128)),
                ('is_public', models.BooleanField(default=True)),
                ('ancestors_are_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('path',),
                'indexes': [models.Index(fields=['name'], name='catalogue_c_name_b785a5_idx'), models.Index(fields=['slug'], name='catalogue_c_slug_f8a9bd_idx'), models.Index(fields=['path'], name='catalogue_c_path_3e8d40_idx'), models.Index(fields=['depth'], name='catalogue_c_depth_eaee69_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True)),
                ('language_code', django_choices_field.fields.TextChoicesField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=2)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalogue.category')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='catalogue_c_categor_4ff1ba_idx')],
                'unique_together': {('language_code', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_set', to='catalogue.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_set', to='products.product')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'ordering': ('product', 'category'),
                'unique_together': {('category', 'product')},
            },
        ),
    ]
