# Generated by Django 5.1.2 on 2024-11-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='catalogue_c_name_b785a5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalogue_c_slug_f8a9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path'], name='catalogue_c_path_3e8d40_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['depth'], name='catalogue_c_depth_eaee69_idx'),
        ),
        migrations.AddIndex(
            model_name='categorytranslation',
            index=models.Index(fields=['category'], name='catalogue_c_categor_4ff1ba_idx'),
        ),
    ]
