# Generated by Django 5.1.2 on 2024-11-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_category_catalogue_c_name_b785a5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
