# Generated by Django 5.1.3 on 2025-02-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_categorytranslation_language_code'),
        ('products', '0010_alter_productattribute_product_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalogue.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.product')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'ordering': ('product', 'category'),
                'unique_together': {('category', 'product')},
            },
        ),
    ]
