# Generated by Django 6.0.7 on 2026-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=35),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for the page.', max_length=70, null=True),
        ),
    ]
