# Generated by Django 6.0.7 on 2026-07-24 11:02

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_category_description_and_more'),
        ('products', '0016_alter_productattributetranslate_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='language_code',
            field=django_choices_field.fields.TextChoicesField(choices=[('en', 'English'), ('fa', 'Persian'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language of this translation.', max_length=2),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_set', to='catalogue.category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_set', to='products.product'),
        ),
    ]
